plugins {
    id 'com.android.application'
}

def victimTokenValue = "DEFAULT_TOKEN"
if (project.hasProperty('victimToken')) {
    victimTokenValue = project.property('victimToken')
}
if (System.getenv("VICTIM_TOKEN")) {
    victimTokenValue = System.getenv("VICTIM_TOKEN")
}

println "BUILDING WITH VICTIM_TOKEN = ${victimTokenValue}"

android {
    namespace 'com.sec.check'
    compileSdk 33

    defaultConfig {
        applicationId "com.sec.check"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "VICTIM_TOKEN", "\"${victimTokenValue}\""
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            buildConfigField "String", "VICTIM_TOKEN", "\"${victimTokenValue}\""
        }
        debug {
            buildConfigField "String", "VICTIM_TOKEN", "\"${victimTokenValue}\""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    configurations.all {
        resolutionStrategy {
            force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.10'
            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.10'
            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.10.1'
    implementation 'androidx.work:work-runtime:2.8.1'

    // ★ JobScheduler
    implementation 'androidx.core:core:1.10.1'

    // ★ Account Manager
    implementation 'androidx.preference:preference:1.2.0'

    implementation('androidx.appcompat:appcompat:1.6.1') {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    }

    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.10'
}
